FROM yanhao98/runner-images:pnpm@sha256:76b78ba219ef18716042da14b6e8b27fac3be0695ab6c0bf4e5bb3381e5d11be

ARG DEBIAN_FRONTEND=noninteractive
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

RUN npx -y playwright install --with-deps && chmod -R 777 /ms-playwright

# https://playwright.dev/docs/docker#usage
# https://mcr.microsoft.com/en-us/product/playwright/about
