FROM yanhao98/runner-images:pnpm@sha256:e9afd31d295f103ae4bd9598466f1bf06d99085133cfd12937ab3ff79608553e

ARG DEBIAN_FRONTEND=noninteractive
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

RUN npx -y playwright install --with-deps && chmod -R 777 /ms-playwright

# https://playwright.dev/docs/docker#usage
# https://mcr.microsoft.com/en-us/product/playwright/about
