FROM debian:bookworm@sha256:b37bc259c67238d814516548c17ad912f26c3eed48dd9bb54893eafec8739c89

ENV SHELL=/bin/bash
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

ARG DEBIAN_FRONTEND=noninteractive
ARG DEPENDENCIES="git ca-certificates zip curl"
RUN set -eux && \
    apt-get update -qq && \
    apt-get install -qq --no-install-recommends --no-install-suggests -y $DEPENDENCIES && \
    rm -rf /var/lib/apt/lists/*

ARG PNPM_VERSION
ARG NODE_VERSION

RUN set -eux && \
    curl -fsSL https://get.pnpm.io/install.sh | sh -

RUN set -eux && \
    pnpm config set store-dir /opt/hostedtoolcache/pnpm-store && \
    pnpm env use --global $NODE_VERSION && \
    pnpm store prune --force && \
    rm -rf $(pnpm sotre path) && \
    echo -n > ~/.bashrc && \
    echo 'alias ls="ls -lhA --color=auto"' >> ~/.bashrc && \
    for command in node npm npx pnpm; do echo -e "$(which $command)\t\e[34m$($command --version)\e[0m"; done

WORKDIR /root
