FROM yanhao98/runner-images:pnpm@sha256:257f9e4ef59a65c1fa04138910627ab4cc7bf004cfb0ad298c30ccfbb3ca37ab

ARG DEBIAN_FRONTEND=noninteractive
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

RUN npx -y playwright install --with-deps && chmod -R 777 /ms-playwright

# https://playwright.dev/docs/docker#usage
# https://mcr.microsoft.com/en-us/product/playwright/about
