name: Build and Push :pnpm
concurrency:
  group: "group-build-and-push-pnpm-${{ github.event_name }}"
  # cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  cancel-in-progress: true
on:
  push:
    branches: [main]
    paths:
      - "Dockerfile.pnpm"
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push-pnpm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Set Variable
        id: set_variable
        run: |
          if [ "${{ github.actor }}" != "nektos/act" ]; then
              echo "cache-to=type=registry,ref=yanhao98/runner-images:pnpm-buildcache,mode=max" >> $GITHUB_OUTPUT
          fi
      - name: Build and Push :pnpm
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile.pnpm
          # cache-from: type=registry,ref=yanhao98/runner-images:pnpm-buildcache
          # cache-to: ${{ steps.set_variable.outputs.cache-to }}
          pull: true
          push: ${{ github.event_name != 'pull_request' && github.actor != 'nektos/act' }}
          tags: yanhao98/runner-images:pnpm
          platforms: linux/amd64,linux/arm64
